# Generated by Django 3.0.6 on 2020-05-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaLoai', models.CharField(max_length=10)),
                ('TenLoai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LoaiSanPham',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaSP', models.CharField(max_length=10)),
                ('TenSP', models.CharField(max_length=300)),
                ('Soluong', models.IntegerField()),
                ('GiaKhoiTao', models.FloatField()),
                ('GiaBan', models.FloatField()),
                ('NgayHetHan', models.DateField()),
                ('Image', models.CharField(max_length=300)),
                ('Mota', models.CharField(max_length=500)),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LoaiSanPham')),
            ],
            options={
                'db_table': 'SanPham',
            },
        ),
    ]
