# Generated by Django 3.0.6 on 2020-05-21 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThanhTien', models.IntegerField(blank=True, default=0, null=True)),
                ('NgayThem', models.DateTimeField(auto_now_add=True)),
                ('dathang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.DatHang')),
                ('sanpham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.SanPham')),
            ],
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiaoHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diachi', models.CharField(max_length=200)),
                ('TinhThanh', models.CharField(max_length=200)),
                ('SoDienThoai', models.CharField(max_length=200)),
                ('NgayThem', models.DateTimeField(auto_now_add=True)),
                ('GhiChu', models.CharField(max_length=1000)),
                ('dathang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.DatHang')),
                ('khachhang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='dathang',
            name='khachhang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Khachhang'),
        ),
    ]
