# Generated by Django 3.0.6 on 2020-05-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200521_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ChiTietDatHang',
        ),
    ]
