# Generated by Django 3.0.6 on 2020-05-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200521_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='ngaythem',
        ),
    ]
