# Generated by Django 3.0.6 on 2020-05-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200526_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
    ]
