# Generated by Django 3.0.6 on 2020-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_product_detail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='name', unique=True),
        ),
    ]
