# Generated by Django 3.0.6 on 2020-05-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_blogcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
