# Generated by Django 3.0.6 on 2020-05-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200527_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='slug',
        ),
    ]
