# Generated by Django 3.0.6 on 2020-05-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_blogcontent_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
